markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "tables"]
pygments: true
auto: true
excerpt_separator: <!--more-->
category_dir: /blog/categories
category_title_prefix: category
#permalink: /blog/posts/:categories/:year/:month/:day/:title.html
permalink: /blog/posts/:year.:month.:day/:title.html
#destination: ./_site/
#plugins:     ./_plugins
#layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['run-jekyll.sh', 'Gemfile*', 'update_site.sh', 'update_site.sh']

url: http://rudametw.github.io
